stages:
  data_ingestion:
    cmd: python src\data\data_ingestion.py
    deps:
    - src\data\data_ingestion.py
    outs:
    - data\raw\raw_data.csv
  data_preprocessing:
    cmd: python src\data_preprocessing\data_preprocessing.py
    deps:
    - data\raw\raw_data.csv
    - src\data_preprocessing\data_preprocessing.py
    outs:
    - data\processed\x_test.csv
    - data\processed\x_train.csv
